name: On Release

on:
  release:
    types:
      - published

jobs:
  Envato_Publisher:
    runs-on: ubuntu-latest
    steps:
      - name: 📩 Fetching Repository
        uses: actions/checkout@v2
      - name: 🚀 Publishing Release To Envato
        uses: varunsridharan/action-envato-publisher@master
        with:
          envato_username: ${{ secrets.envato_username }}
          envato_personal_token: ${{ secrets.envato_token }}
          custom_command: "composer install --no-dev"
          exclude_list: "/src/ gulpfile.js gulp-config.js composer.lock composer.json wp-pot.json envato_assets_exclude_list.txt .envatoassets .gitignore .editorconfig vendor/*/*/README.md vendor/*/*/.gitignore"
      - name: 📦 Upload ZIP To Release in Github
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🐦 Tweet
        uses: m1ner79/Github-Twittction@master
        with:
          twitter_status:  ${{ secrets.TWITTER_MSG }}
          twitter_consumer_key: ${{ secrets.TWITTER_API_KEY }}
          twitter_consumer_secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
          twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 
