name: On Release

on:
  push:
    tags:
      - "*"

jobs:
  Envato_Publisher:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Repository
        uses: actions/checkout@v1
      - name: Publishing Release To Envato
        uses: varunsridharan/action-envato-publisher@master
        with:
          envato_username: ${{ secrets.envato_username }}
          envato_personal_token: ${{ secrets.envato_token }}
          custom_command: "composer install --no-dev"
          exclude_list: "/src/ gulpfile.js gulp-config.js composer.lock composer.json wp-pot.json envato_assets_exclude_list.txt .envatoassets .gitignore .editorconfig vendor/*/*/README.md vendor/*/*/.gitignore"
      - name: Upload ZIP To Release in Github
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WordPress_Publisher:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Repository
        uses: actions/checkout@v2
      - name: Installing Composer
        uses: pxgamer/composer-action@master
        with:
          command: install --no-dev
      - name: Publishing Release To WordPress
        uses: varunsridharan/action-wp-org-deploy@master
        with:
          WORDPRESS_PASSWORD: ${{ secrets.WP_PASSWORD }}
          WORDPRESS_USERNAME: ${{ secrets.WP_USERNAME }}
          SLUG: ${{ secrets.WP_SLUG }}
      - name: Upload ZIP To Release in Github
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
